---
title: "Conceptual Timeline"
author: "Jen Baron"
date: "Jan 12 2022"
output: html_document
---

#Load Packages

```{r}
library(ggplot2)
library(scales)
library(dplyr)
library(ggrepel)
library(ggbreak)
library(nationalparkcolors)
library(stringr)
library(ggfittext)
library(ggpubr)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(ggprism)
library(extrafont)
#loadfonts(); windowsFonts()
```

```{r}

```

https://pharmacoecon.me/post/2021-04-18-timeline-graph/

# Timeline

## Phases

```{r}
phases <- data.frame(
  start = c(1500, 1850, 1919, 1940, 2003),
  end = c(1850, 1919, 1940, 2003, 2021),
  phase=as.factor(c("Indigenous fire stewardship", "Early colonization", "Active but altered", "Fire suppression era", "Modern era"))
)

phases$phase <- factor(phases$phase, levels = c("Indigenous fire stewardship", "Early colonization", "Active but altered", "Fire suppression era", "Modern era")) 
  
changes <- data.frame(
  change = c(1850, 1919, 1940, 2003, 2022))
```

```{r}
pal <- park_palette("MtMckinley")

ggplot() +
  #colored rectangles (phases)
  geom_rect(data=phases, 
              aes(xmin=start, xmax=end, ymin=-Inf, ymax=Inf,
                  fill=phase), alpha=0.5) +
  #dashed breakpoints
  geom_vline(data=changes, aes(xintercept=change), linetype = "dashed") +
  #custom colours
  scale_fill_manual(values = pal, name = "", 
                    labels=function(x) str_wrap(x, width=15)) +
  scale_x_continuous(breaks=c(1500, 1850, 1919, 1940, 2003), limits = c(1500, 2021)) +
  scale_y_continuous(limits=c(0,0.6)) +
  #break axis
  scale_x_break(c(1520, 1830)) +
  #scale_x_break(c(1870, 1910)) +
  #theme customization
  theme_classic() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.line.x = element_line(arrow = grid::arrow(length = unit(0.3, "cm"),
                                                       ends = "last")))
```
## Milestones

```{r}
phases2 <- data.frame(
  start = c(1820, 1850, 1919, 1940, 2003, 2022),
  end = c(1850, 1919, 1940, 2003, 2022, 2040),
  phase=as.factor(c("Indigenous fire stewardship", "Early colonization", "Active but altered fire regime", "Fire suppression era", "Modern era", "Future fire (uncertain)"))
)

phases2$phase <- factor(phases2$phase, levels = c("Indigenous fire stewardship", "Early colonization", "Active but altered fire regime", "Fire suppression era", "Modern era", "Future fire (uncertain)")) 

milestones <- data.frame(
  year = c(1910, 1931, 1985, 2003, 2017, 2018),
  label = c(1910, 1931, 1985, 2003, 2017, NA),
  milestone = c("The 'Great Burn' threatens town of Cranbrook",
                "Largest area burned on record",
                "Multiple fires escape suppression",
                "'Firestorm' threatens communities",
                "Back-to-back record-breaking fire seasons",
                "")) %>%
  mutate(
    # Specify y-direction for milestone
    position = c(0.05, 0.3, 0.01, 0.13, .26, .2), 
    # Specify text position
    text_position = 0.077 + position)
```


```{r}
fig.milestones <- ggplot() +
  #colored rectangles (phases)
  geom_rect(data=phases2, 
              aes(xmin=start, xmax=end, ymin=-Inf, ymax=Inf,
                  fill=phase), alpha=0.5) +
  #dashed breakpoints
  geom_vline(data=changes, aes(xintercept=change), linetype = "dashed") +
   #add milestones
  geom_segment(data=milestones, aes(x=year,y=position,xend=year, yend=-Inf), 
               color='black', size=0.4) +
  geom_point(data = milestones, aes(x=year,y=position), size=1.5) + 
  #add labels
  geom_text(data=milestones, 
            aes(x=year,y=position+0.02,label=label, fontface="bold"),size=4,
            color='black',family="Georgia") + 
  annotate("text", x=2022, y=0.22, label="2018", fontface="bold",size=4, #add 2018 label manually
            color='black',family="Georgia") +
  geom_label_repel(data = milestones,
                  aes(x=year,y=text_position,label=str_wrap(milestone,16)),
                  size=3,
                  point.size=NA, family="Georgia")  +
  #custom colours
  scale_fill_manual(values = pal, name = "", 
                    labels=function(x) str_wrap(x, width=15)) +
  scale_x_continuous(breaks=c(1850, 1919, 1940, 2003, 2022), 
                     limits = c(1820, 2040),expand = c(0, 0),
                     guide = "prism_minor", minor_breaks = seq(1820, 2030, 10)) + #minor breaks
  scale_y_continuous(limits=c(0,0.4)) +
  labs(fill = "Phase") +
  #theme customization
  theme_bw() +
  theme(text = element_text(family = "Georgia"),
        legend.position = "bottom",
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(),
        axis.line.y = element_blank(), 
        axis.text.x = element_text(face="bold", size="16"),
        legend.text = element_text(size="11", family="Georgia"),
        prism.ticks.length.x = unit(4, "pt"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.line.x = element_line(size=0.5, 
                                   arrow = grid::arrow(length = unit(0.4, "cm"),
                                                       ends = "last")))
fig.milestones

```

## Descriptive phases
```{r}
phases2 <- phases2 %>% mutate(
  mid = start+(((end-start)/2)),
  text = c(
  "Frequent, low- & mixed-severity surface fire regime",
  "Indigenous burning replaced by land-clearance and early settlement",
  "Settler resource extraction drives an active fire regime",
  "Fire suppression and timber management create fire deficit & fuel accumulation",
  "Fire deficit interacts with extreme fire weather to escape suppression",
  "Projected increases in extreme fire behaviour & fire effects"))

changes <- changes %>%
  mutate(
    text = c("Euro-Canadian colonization",
              NA,
              "Widespread fire suppression",
              "Climate & fuels tipping point",
             NA))
```

```{r}
fig.desc <- ggplot() +
  geom_rect(data=phases2, 
              aes(xmin=start, xmax=end, ymin=0, ymax=1,
                  fill=phase), alpha=0.5) +
  geom_fit_text(data=phases2, #fits text to size of rectangles
                aes(xmin=start, xmax=end,
                    ymin=0, ymax=1,label=text), 
                reflow=TRUE,family="Georgia")+
  geom_vline(data=changes, aes(xintercept=change), linetype = "dashed") +
  geom_label(data=changes, aes(x=change, y=0.9, label=str_wrap(text,15)),family="Georgia") +
  scale_x_continuous(breaks=c(1850, 1919, 1940, 2003), 
                     limits = c(1820, 2040),expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0,0)) +
  scale_fill_manual(values = pal, name = "", 
                    labels=function(x) str_wrap(x, width=20)) +
  guides(fill = guide_legend(nrow=1)) +
  theme_bw() +
  theme(text=element_text(family="Georgia"), legend.position = "none",
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text = element_text(size="11"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
fig.desc
```

## Drivers & Methods

```{r}
drivers <- data.frame(
  start = c(1850,1919, 1940, 1970, 1990),
  end = c(2022, 2022, 2022, 2022, 2022),
  upper = c(0.9, 0.8, 0.7, 0.6, 0.5),
  lower = c(.82, 0.72, 0.62, 0.52, 0.42),
  driver=as.factor(c("Elimination of Indigenous fire through colonization", "Timber management","Fire suppression paradigm","WUI & communities", "Climate change")))

future.drivers <- data.frame(
  start = 2022,
  end = 2040,
  upper = c(0.9, 0.8, 0.7, 0.6, 0.5),
  lower = c(.82, 0.72, 0.62, 0.52, 0.42),
  driver=as.factor(c("Elimination of Indigenous fire through colonization", "Timber management","Fire suppression paradigm","WUI & communities", "Climate change")))

methods <- data.frame(
  chapter = c("Chapter 1", "Chapter 2", "Chapters 3 & 4"),
  change = c("Fire deficit",
           "Fuel accumulation", 
           "Fire behaviour & risk"),
  start = c(1919, 1950, 1950),
  end = c(2019, 2016, 2038),
  drivers = c("Historical fire frequency & 20th century fire suppression",
            "Fire suppression, forest management", 
           "Fire deficit, fuel accumulation, and values at risk"),
  method = c("Chapter 1: Fire perimeters",
           "Chapter 2: Historical air photos", 
           "Chapters 3 & 4: Simulation modelling"),
  upper = c(0.32, 0.22, 0.12),
  lower = c(.24, 0.14, 0.04))
```

```{r}
fig.drivers <- ggplot() +
  #phases
  geom_rect(data=phases2, 
              aes(xmin=start, xmax=end, ymin=0, ymax=1,
                  fill=phase), alpha=0.5) +
  scale_fill_manual(values = pal, name = "", 
                    labels=function(x) str_wrap(x, width=20)) +
  #vline & hline
  geom_vline(data=changes, aes(xintercept=change), linetype = "dashed")  +
  #geom_hline(data=changes, aes(yintercept=0.4), size=.3)  +
  #drivers
  geom_rect(data=drivers, aes(xmin = start, xmax = end, 
              ymin = lower, ymax = upper),
            col = "saddlebrown", fill = "white", size=0.75, alpha=0.6) +
  geom_fit_text(data=drivers,aes(xmin=start, xmax=end, 
                                 ymin=lower, ymax=upper,
                                 label=driver), family="Georgia") +
  geom_rect(data=future.drivers, aes(xmin = start, xmax = end, 
              ymin = lower, ymax = upper),
            col = "gray50", fill = "white", size=0.75, alpha=0.6, 
            linetype="dotted") +
  #methods
  geom_rect(data=methods, aes(xmin = start, xmax = end, 
              ymin = lower, ymax = upper, col = chapter),
            fill = "white", size=0.75, alpha=0.6) +
  geom_fit_text(data=methods,aes(xmin=start, xmax=end, 
                                 ymin=lower, ymax=upper,
                                 label=method),family="Georgia") +
  scale_color_manual(values=c("firebrick4","darkorange3","darkgoldenrod"), guide="none") +
  #text labels
  #annotate("text", x=1825, y=0.92, label="Drivers", family="Georgia", size=5, hjust=0) + #fontface=2
  #annotate("text", x=1825, y=0.37, label="Methods", family="Georgia", size=5, hjust=0) +
  #theme
  scale_x_continuous(breaks=c(1850, 1919, 1940, 2003), 
                     limits = c(1820, 2040),expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0,0)) +
  guides(fill = guide_legend(nrow=1)) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text = element_text(size="11", family="Georgia"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
fig.drivers
        
```





## Combine

```{r}
fig.timeline <- ggarrange(fig.desc,fig.milestones,
          nrow=2, common.legend=TRUE, legend = "top")
fig.timeline

ggsave("figures/3_timeline.png", fig.timeline, dpi=300, width=10, height=7)
```

```{r}
fig.timeline2a <- ggarrange(fig.desc,fig.drivers,fig.milestones,
          nrow=3, common.legend=TRUE, legend = "top")
fig.timeline2a

ggsave("figures/3_timeline2a.png", fig.timeline2a, dpi=300, width=10, height=10)
```
```{r}
fig.timeline2b <- ggarrange(fig.drivers, fig.desc, fig.milestones,
          nrow=3, common.legend=TRUE, legend = "top")
fig.timeline2b

ggsave("figures/3_timeline2b.png", fig.timeline2b, dpi=300, width=10, height=10)
```




# Diagram





```{r}
#C [label = 'Mild 20th\n century climate']
#I [label = 'Technological\n advancement']
#J [label = 'Social & ecological\n values'] #J->4
#K [label = 'Fire season\n length'] #E->K K->3 

#G->J G->4 G->A additional WUI interactions
#D->A B->A drivers of fire suppression paradigm

pathways <- grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 12]

  # several 'node' statements
  node [shape = box, fontname = Georgia, margin=0.2]
F [label = 'Extreme fire\n weather']
H [label = 'Increasing\n lightning ignitions']
M [label = 'Fuel type\n transitions']
L [label = 'Human\n ignitions']

  node [width=1, height=1, 
fontsize=14, color=saddlebrown, penwidth=2]
D [label = 'Elimination of \nIndigenous fire\n through colonization']
A [label = 'Fire suppression\n paradigm']
B [label = 'Timber\n management']
E [label = 'Climate change']
G [label = 'WUI\n & communities']

  node [shape = circle,
        fixedsize = true, width = 2, 
        color=darkorange3,penwidth=2, fontsize=16] 
  1 [label = 'Chapter 2:\n Fuel accumulation']

  node [color=firebrick4] 
  2 [label = 'Chapter 1:\n Fire deficit']

  node [color=darkgoldenrod] 
  3 [label = 'Chapters 3 & 4:\n Fire behaviour']

  node[shape = circle, fixedsize = true,
        width = 2, color=black]
  4 [label = 'Synthesis:\n Contemporary\n fire risk']

  # several 'edge' statements
  A->M A->2 D->2 
  E->H  D->A B->A
  1->4 2->4 E->F F->3 2->1
  H->3 3->4 1->3 
  G->M M->1 B->M E->M M->3
  G->L L->3 
}
")
pathways 
```

```{r}
pathways %>%
    export_svg() %>%
    charToRaw %>%
    rsvg_png("figures/4_pathways.png")
```

## Archive

```{r}
graph1 <- grViz("
digraph boxes_and_circles {
  # a 'graph' statement
  graph [overlap = true, fontsize = 12]
  # several 'node' statements
  node [shape = box,
        fontname = Georgia]
A [label = 'Fire suppression\n paradigm']
B [label = 'Timber management']
C [label = 'Mild 20th\n century climate']
D [label = 'Elimination of Indigenous fire\n through colonization']
E [label = 'Climate change']
F [label = 'Extreme fire weather']
G [label = 'Wildland-urban interface\n & communities']
H [label = 'Increasing\n lightning ignitions']
I [label = 'Post-WWII technologies']
J [label = 'Social & ecological values']
K [label = 'Fire season length']
L [label = 'Complex topography']
  node [shape = circle,
        fixedsize = true,
        width = 1.7, color=darkorange,penwidth=2] 
1 [label = 'Fuel accumulation']
  node [shape = circle,
        fixedsize = true,
        width = 1.7, color=maroon,penwidth=2] 
2 [label = 'Fire deficit']
  node [shape = circle,
        fixedsize = true,
        width = 1.7, color=gold] 
3 [label = 'Fire behaviour']
  node[shape = triangle, width=2.5, height=2.5, color=black]
4 [label = 'Contemporary\n fire risk']
  # several 'edge' statements
  A->1 A->2 C->A B->1 D->2 B->A
  E->K K->4 L->3  D->A E->H
  1->4 2->4 E->F F->3 G->2 2->1
  G->4 H->3 I->A 3->4 1->3 J->4
}
")
graph1
```

```{r}
legend <- grViz("
digraph boxes_and_circles {

node [shape = box, width=1, height=.7, 
fontsize=14, color=saddlebrown]
A [label = 'Driver']

  node [shape = circle,
        fixedsize = true,
        width = 1.2, color=black] 
B [label = 'Consequence']

  node [shape = circle,
        fixedsize = true,
        width = 1, color=firebrick4] 
2 [label = 'Chapter 1']

  node [shape = circle,
        fixedsize = true,
        width = 1, color=darkorange3] 
1 [label = 'Chapter 2']


  node [shape = circle,
        fixedsize = true,
        width = 1, color=darkgoldenrod] 
3 [label = 'Chapters\n 3 & 4']

A->B B->2 B->1 B->3

}
")

legend
```







**Try to create NDF & EDF to customize displays**

Not working right now - 


```{r}
nodes_1 <- create_node_df(n=12,
                      nodes = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"),
                      label=c("Fire suppression paradigm", 
                              "Timber management", 
                              "Mild 20th century climate",
                              'Loss of Indigenous fire\n through colonization',
                              'Climate change',
                              'Extreme fire weather',
                              'Wildland-urban interface\n & communities',
                              'Increasing\n lightning ignitions',
                              'Post-WWII technologies',
                              'Social & ecological values',
                              'Fire season length',
                              'Complex topography' ),
                      color = "black",
                      shape = "box")

nodes_2 <- create_node_df(n=4,
                          nodes = 13:16,
                          label=c("Fuel accumulation", "Fire deficit", "Fire behaviour", "Contemporary\n fire risk"),
                          color = c("darkorange", "maroon", "gold", "black"),
                          shape=c("circle", "circle", "circle", "triangle"))

ndf <- rbind(nodes_1, nodes_2)

#currently not working with letters
edf <- create_edge_df(from = c("A", "A", "C", "B", "D", "B",
                               "E", "K", "L", "D", "E",
                               13, 14, "E", "F", "G", 14,
                               "G", "H", "I", 15, 13, "J"),
                      to = c(13, 14, "A", 13, 14, "A",
                             "K", 16, 15, "A", "H",
                             16, 16, "F", 15, 14, 13,
                             16, 15, "A", 16, 15, 16))

```


```{r}
graph <- create_graph(nodes_df = ndf,
                      edges_df = edf)
graph %>% render_graph()
```




# Reproducibility

```{r}
git2r::repository()
Sys.time()
sessionInfo()
```



